/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as StartRouteImport } from './routes/start'
import { Route as SpecificRouteImport } from './routes/specific'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EarlyAccessRouteImport } from './routes/early-access'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SamplesIndexRouteImport } from './routes/samples.index'
import { Route as StudyDoneRouteImport } from './routes/study.done'
import { Route as SamplesIdRouteImport } from './routes/samples.$id'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminEvalsRouteImport } from './routes/admin.evals'
import { Route as AdminDinnerRouteImport } from './routes/admin.dinner'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecificRoute = SpecificRouteImport.update({
  id: '/specific',
  path: '/specific',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesIndexRoute = SamplesIndexRouteImport.update({
  id: '/samples/',
  path: '/samples/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDoneRoute = StudyDoneRouteImport.update({
  id: '/study/done',
  path: '/study/done',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesIdRoute = SamplesIdRouteImport.update({
  id: '/samples/$id',
  path: '/samples/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvalsRoute = AdminEvalsRouteImport.update({
  id: '/admin/evals',
  path: '/admin/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDinnerRoute = AdminDinnerRouteImport.update({
  id: '/admin/dinner',
  path: '/admin/dinner',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/early-access': typeof EarlyAccessRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/specific': typeof SpecificRoute
  '/start': typeof StartRoute
  '/unlock': typeof UnlockRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why': typeof WhyRoute
  '/admin/dinner': typeof AdminDinnerRoute
  '/admin/evals': typeof AdminEvalsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/samples/$id': typeof SamplesIdRoute
  '/study/done': typeof StudyDoneRoute
  '/samples/': typeof SamplesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/early-access': typeof EarlyAccessRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/specific': typeof SpecificRoute
  '/start': typeof StartRoute
  '/unlock': typeof UnlockRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why': typeof WhyRoute
  '/admin/dinner': typeof AdminDinnerRoute
  '/admin/evals': typeof AdminEvalsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/samples/$id': typeof SamplesIdRoute
  '/study/done': typeof StudyDoneRoute
  '/samples': typeof SamplesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/early-access': typeof EarlyAccessRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/specific': typeof SpecificRoute
  '/start': typeof StartRoute
  '/unlock': typeof UnlockRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/why': typeof WhyRoute
  '/admin/dinner': typeof AdminDinnerRoute
  '/admin/evals': typeof AdminEvalsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/samples/$id': typeof SamplesIdRoute
  '/study/done': typeof StudyDoneRoute
  '/samples/': typeof SamplesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/early-access'
    | '/help'
    | '/history'
    | '/home'
    | '/login'
    | '/privacy'
    | '/results'
    | '/scan'
    | '/signup'
    | '/specific'
    | '/start'
    | '/unlock'
    | '/unsubscribe'
    | '/why'
    | '/admin/dinner'
    | '/admin/evals'
    | '/admin/stats'
    | '/samples/$id'
    | '/study/done'
    | '/samples/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/early-access'
    | '/help'
    | '/history'
    | '/home'
    | '/login'
    | '/privacy'
    | '/results'
    | '/scan'
    | '/signup'
    | '/specific'
    | '/start'
    | '/unlock'
    | '/unsubscribe'
    | '/why'
    | '/admin/dinner'
    | '/admin/evals'
    | '/admin/stats'
    | '/samples/$id'
    | '/study/done'
    | '/samples'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/early-access'
    | '/help'
    | '/history'
    | '/home'
    | '/login'
    | '/privacy'
    | '/results'
    | '/scan'
    | '/signup'
    | '/specific'
    | '/start'
    | '/unlock'
    | '/unsubscribe'
    | '/why'
    | '/admin/dinner'
    | '/admin/evals'
    | '/admin/stats'
    | '/samples/$id'
    | '/study/done'
    | '/samples/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultsRoute: typeof ResultsRoute
  ScanRoute: typeof ScanRoute
  SignupRoute: typeof SignupRoute
  SpecificRoute: typeof SpecificRoute
  StartRoute: typeof StartRoute
  UnlockRoute: typeof UnlockRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WhyRoute: typeof WhyRoute
  AdminDinnerRoute: typeof AdminDinnerRoute
  AdminEvalsRoute: typeof AdminEvalsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  SamplesIdRoute: typeof SamplesIdRoute
  StudyDoneRoute: typeof StudyDoneRoute
  SamplesIndexRoute: typeof SamplesIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specific': {
      id: '/specific'
      path: '/specific'
      fullPath: '/specific'
      preLoaderRoute: typeof SpecificRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/': {
      id: '/samples/'
      path: '/samples'
      fullPath: '/samples/'
      preLoaderRoute: typeof SamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/done': {
      id: '/study/done'
      path: '/study/done'
      fullPath: '/study/done'
      preLoaderRoute: typeof StudyDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$id': {
      id: '/samples/$id'
      path: '/samples/$id'
      fullPath: '/samples/$id'
      preLoaderRoute: typeof SamplesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evals': {
      id: '/admin/evals'
      path: '/admin/evals'
      fullPath: '/admin/evals'
      preLoaderRoute: typeof AdminEvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dinner': {
      id: '/admin/dinner'
      path: '/admin/dinner'
      fullPath: '/admin/dinner'
      preLoaderRoute: typeof AdminDinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResultsRoute: ResultsRoute,
  ScanRoute: ScanRoute,
  SignupRoute: SignupRoute,
  SpecificRoute: SpecificRoute,
  StartRoute: StartRoute,
  UnlockRoute: UnlockRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WhyRoute: WhyRoute,
  AdminDinnerRoute: AdminDinnerRoute,
  AdminEvalsRoute: AdminEvalsRoute,
  AdminStatsRoute: AdminStatsRoute,
  SamplesIdRoute: SamplesIdRoute,
  StudyDoneRoute: StudyDoneRoute,
  SamplesIndexRoute: SamplesIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
